export enum ErrorCode {
  INVALID_SESSION = 'INVALID_SESSION',
  REPLAY = 'REPLAY',
  OUT_OF_RANGE = 'OUT_OF_RANGE',
  INVALID_QR = 'INVALID_QR',
  MISSING_SELFIE = 'MISSING_SELFIE',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL = 'INTERNAL',
}
